#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  fogg
  tf init "$@"
}

source sub "$BASH_SOURCE" "$@"
