#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  fogg default
  tf init -backend-config terraform-init.tfvars "$@"
}

source sub "$BASH_SOURCE" "$@"
