#!/usr/bin/env bash

function remote_bucket {
  echo "b-$(hcltool terraform.tfvars  | jq -r '.s3_remote_state' | cut -d- -f2)-global-tf-remote-state"
}

function remote_region {
  hcltool $adj_config/terraform.tfvars | jq -r '.aws_region'
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local pth_config="$(echo "$PWD" | perl -pe 's{.*?/org/}{}; s{/+}{-}g')"
  local adj_config="./$(echo "$pth_config" | perl -pe 's{[^-]+$}{}; s{[^-]+}{..}g; s{-}{/}g')"

  terraform remote config -backend=s3 \
    -backend-config="bucket=$(remote_bucket)" \
    -backend-config="region=$(remote_region)" \
    -backend-config="key=$pth_config/terraform.tfstate"
}

source sub "$BASH_SOURCE" "$@"
