#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local id_tfvars="$(pwd)"
  id_tfvars="org--$(echo "${id_tfvars#*/org/}" | perl -pe 's{/}{--}g')/terraform.tfvars"
  
  if [[ -n "${1:-}" ]]; then
    if [[ -f "$1" ]]; then
      credstash put -a "$id_tfvars" "$(cat "$1")"
      return
    fi
    
    id_tfvars="$1"; shift
    if [[ -f "${1:-}" ]]; then
      credstash put -a "$id_tfvars" "$(cat "$1")"
      return
    fi
  fi

  local tmp_config="$(mktemp -t XXXXXX)"
  local tmp_config2="$(mktemp -t XXXXXX)"
  trap "$(printf 'rm -f %q %q' "$tmp_config" "$tmp_config2")" EXIT
  credstash get "$id_tfvars" > "$tmp_config"
  cp "$tmp_config" "$tmp_config2"
  ${VISUAL:-${EDITOR:-vi}}  "$tmp_config"
  if ! diff "$tmp_config" "$tmp_config2"; then
    credstash put -a "$id_tfvars" "$(cat "$tmp_config")"
    fogg
  fi
}

source sub "$BASH_SOURCE" "$@"
