#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local pth_root="$(cd "$(git rev-parse --show-cdup)" && pwd)"

  local env="$(cat .terraform/environment 2>/dev/null || echo default)"
  local parts=()
  while true; do
    if [[ "$(pwd)" == "$pth_root" ]]; then
      parts=( "$(cat .terraform/environment 2>/dev/null || echo default)" ${parts[@]:-} )
      break
    else
      parts=( "$(basename $(pwd))" ${parts[@]:-} )
    fi
    cd ..
  done
  echo "$env ${parts[@]}" | sed 's# #/#g'
}

source sub "$BASH_SOURCE" "$@"
