#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  ln -nfs ../app-xxx/env.tf .
  ln -nfs ../app-xxx/app.tf .
  ln -nfs ../app-xxx/service.tf .
  ln -nfs ../app-xxx/fogg.tf .
}

source sub "$BASH_SOURCE" "$@"
