#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local mac="$(curl -s http://169.254.169.254/latest/meta-data/mac)"

  export AWS_KEYPAIR="$(curl -s http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key | awk '{print $NF}')"
  export AWS_SUBNET="$(curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/$mac/subnet-id)"
  export AWS_SG="$(curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/$mac/security-group-ids | xargs)"
  export AWS_SG_COMMA="${AWS_SG// /,}"

  exec "$@"
}

source sub "$BASH_SOURCE" "$@"
