#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ "$#" -gt 0 ]]; then
    echo "ERROR: this command doesn't take arguments" 1>&2
    return 1
  fi

  local nm_module="$(cat .fogg-module 2>/dev/null || true)"
  if [[ -z "${nm_module}" ]]; then
    case "$(git rev-parse --show-cdup)" in
      "") nm_module="org" ;;
      ../) nm_module="global" ;;
      ../../) nm_module="app" ;;
      ../../../) nm_module="svc" ;;
      *)
        echo "ERROR: unknown fogg module" 1>&2
        return 1
        ;;
    esac
  fi

  local nm_config="$(fogg name | cut -d: -f1)"
  local nm_rest="$(echo "$nm_config" | cut -s -d: -f2)"

  local nm_env="$(echo "$nm_config" | cut -s -d/ -f1)"
  local nm_org="$(echo "$nm_config" | cut -d/ -f2)"
  local nm_app="$(echo "$nm_config" | cut -s -d/ -f4)"
  local nm_service="$(echo "$nm_config" | cut -s -d/ -f5)"

  fogg gen "$nm_module" "$nm_org" "$nm_env" "$nm_app" "$nm_service" "$nm_rest"
}

source sub "$BASH_SOURCE" "$@"
