#!/usr/bin/env bash

function main {
  local shome="${_fogg_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  local nm_env="$(basename "$(pwd)" | cut -d- -f1-3)"
  ln -nfs ../env-xxx/env.tf .
  ln -nfs ../env-imma-dev/env-remote-state.tf .
}

source sub "$BASH_SOURCE" "$@"
