#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source normalize

  local id_credstash_org="org/$(cat .fogg-name | cut -d/ -f1)"
  local id_credstash_local="$(cat .fogg-name)"

  local tmp_org="$(mktemp -t XXXXXX)"
  local tmp_local="$(mktemp -t XXXXXX)"
  local tmp_config="$(mktemp -t XXXXXX)"

  trap "$(printf 'rm -f %q %q %q' "$tmp_org" "$tmp_config" "$tmp_local")" EXIT

  credstash get "$id_credstash_org" > "$tmp_org" 2>/dev/null &
  credstash get "$id_credstash_local" > "$tmp_local" 2>/dev/null &
  wait

  if [[ ! -s "$tmp_local" ]]; then
    echo '{}' > "$tmp_local"
  fi

  local nm_config="$(cat .fogg-name | cut -d/ -f3-)"
  if [[ -z "$nm_config" ]]; then
    nm_config="$(cat .fogg-name | cut -d/ -f2)"
    if [[ -z "$nm_config" ]]; then
      nm_config="$(cat .fogg-name | cut -d/ -f1)"
    fi
  fi

  cat "$tmp_org" | jq \
    --arg org "$(cat .fogg-name | cut -d/ -f1)" \
    --arg env "$(cat .fogg-name | cut -d/ -f2)" \
    --arg config "$nm_config" \
    --argfile local "$tmp_local" \
    '.[$org].inherit + .[$env].inherit + .[$config].inherit + .[$config].vars + $local' | jq -S . > "$tmp_config"

  cat "$tmp_config"
}

source sub "$BASH_SOURCE" "$@"
