#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local id_tfvars="$(fogg name)"

  exec credstash get "$id_tfvars" "$@"
}

source sub "$BASH_SOURCE" "$@"
