#!/usr/bin/env bash

function init_service {
  local nm_app="${nm_service#*-}"
  nm_app="${nm_app%-*}"

  if [[ -d "$HOME/work/${nm_app}" ]]; then
    pushd "$HOME/work/${nm_app}" ]] >/dev/null
    source "$_block_home/script/profile" ''
    block meta clone
    require
    popd >/dev/null
  fi

  if [[ -f "Blockfile.json" ]]; then
    source "$_block_home/script/profile" ''
    require
  fi

  cd "${_org_home}/${nm_service}"
  block require "$@"
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_service="${0##*/}"

  case "${1:-}" in
    list)
      shift
      if [[ "$#" -gt 0 ]]; then
        init_service deploy "$@" --list-hosts
      else
        "$0" list-all
      fi
      ;;
    deploy)
      shift
      init_service deploy "$@"
      ;;
    init|plan|apply|blue|green|live|staging)
      "$0" fogg "$@"
      ;;
    refresh)
      "$0" terraform "$@"
      ;;
    git|make|fogg|terraform|vagrant|block)
      init_service "$@"
      ;;
    "")
      figlet terraform
      "$0" terraform output
      "$0" list-all
      ;;
    list-all)
      local tmp_list="$(mktemp -d -t XXXXXX)"

      "$0" list blue 2>/dev/null > "$tmp_list/blue" &
      "$0" list green 2>/dev/null > "$tmp_list/green" &
      "$0" list fogg 2>/dev/null > "$tmp_list/fogg" &
      wait 

      figlet blue
      cat "$tmp_list/blue" 

      figlet green
      cat "$tmp_list/green" 

      figlet all
      cat "$tmp_list/fogg" 

      rm -rf "$tmp_list"
      ;;
    *)
      echo "ERROR: unknown sub-command: $*" 1>&2
      false
      ;;
  esac
}

source sub "$BASH_SOURCE" "$@"
