#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local pth_root="$(cd "$(git rev-parse --show-cdup)" && pwd)"

  local env="$(cat .terraform/environment 2>/dev/null || echo default)"
  local parts=()
  local cnt_parts=0
  while true; do
    if [[ "$(pwd)" == "$pth_root" ]]; then
      if [[ "$cnt_parts" == 0 ]]; then
        env=
      fi
      parts=( "$(cat .terraform/environment 2>/dev/null || echo default)" ${parts[@]:-} )
      break
    else
      parts=( "$(basename $(pwd))" ${parts[@]:-} )
      cnt_parts="$(( cnt_parts + 1 ))"
    fi
    cd ..
  done
  echo "${env:+${env}}/${parts[@]}" | sed 's#^default/#/#; s# #/#g'
}

source sub "$BASH_SOURCE" "$@"
