#!/usr/bin/env bash

function main {
  local shome="${_fogg_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  ln -nfs ../app-xxx/env.tf .
  ln -nfs ../app-xxx/service.tf .
}

source sub "$BASH_SOURCE" "$@"
