#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ "$#" == 0 ]]; then
    set -- list
  fi

  fogg account tf workspace "$@"
}

source sub "$BASH_SOURCE" "$@"
