#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_workspace="$1"; shift

  if [[ ! -f ".terraform/environment" ]]; then
    mkdir -p .terraform
    echo "$nm_workspace" > ".terraform/environment"
    fogg default
    fogg account fogg init -lock=false
  else
    fogg account tf workspace \select "$nm_workspace" # that \s is a ridiculous workaround to syntax hilighting
    fogg default
  fi

  if [[ "$#" -gt 0 ]]; then
    fogg account fogg "$@"
  fi
}

source sub "$BASH_SOURCE" "$@"
