#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local remote_path="$(pwd -P | perl -pe 's{^.*?/org/(.*)}{$1}; s{/instances/}{/}; s{/}{_}g')/terraform.tfstate"
  local nm_org="$(pwd -P | perl -pe 's{^.*?/org/([^/]+).*$}{$1}')"
  local remote_bucket="$(credstash get org--immanent | jq -r '.remote_bucket')"

  aws dynamodb get-item --table-name terraform_state_lock --key "$(jq -n --arg remote "${remote_bucket}/${remote_path}" '{LockID: {S: "\($remote)-md5"}}')"
  aws dynamodb delete-item --table-name terraform_state_lock --key "$(jq -n --arg remote "${remote_bucket}/${remote_path}" '{LockID: {S: "\($remote)-md5"}}')"
}

source sub "$BASH_SOURCE" "$@"


