#!/usr/bin/env bash

function remote_bucket {
  local id_account="$(hcltool terraform.tfvars 2>/dev/null | jq -r '.s3_remote_state//""' | cut -d- -f2)"

  if [[ -z "${id_account}" ]]; then
    id_account="$(cat $adj_config/.terraform/terraform.tfstate 2>/dev/null | jq -r '.modules | map(.outputs.s3_remote_state.value//"") | unique[]' | cut -d- -f2)"
  fi
  
  echo "b-${id_account}-global-tf-remote-state"
}

function remote_region {
  hcltool $adj_config/terraform.tfvars | jq -r '.aws_region'
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  fogg

  local pth_config="$(echo "$PWD" | perl -pe 's{.*[/-]org/}{}; s{/+}{-}g')"
  local adj_config="./$(echo "$pth_config" | perl -pe 's{[^-]+$}{}; s{[^-]+}{..}g; s{-}{/}g')"

  terraform remote config -backend=s3 \
    -backend-config="bucket=$(remote_bucket)" \
    -backend-config="region=$(remote_region)" \
    -backend-config="key=$pth_config/terraform.tfstate"
}

source sub "$BASH_SOURCE" "$@"
