#!/usr/bin/env bash

function gen {
  local tmp_state="$1"; shift
  local tmp_seed="$1"; shift
  local tmp_modules="$1"; shift
  local nm_env="$1"; shift
  local nm_app="$1"; shift
  
  local az_count="$(hcltool terraform.tfvars | jq -r '.az_count')"

	jq -n \
        --argfile state        "$tmp_state" \
        --argfile seed     "$tmp_seed" \
        --argfile modules  "$tmp_modules" \
        --arg     az_count     "$az_count" \
	      --arg     env_name "$nm_env" \
        --arg     app_name "$nm_app" \
        '$state * $seed * $modules | .variable |= .*
            { az_count:            { default: "\($az_count)" },
              env_name:            { default: "\($env_name)" },
              app_name:            { default: "\($app_name)" }
            }'
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source _fogg "$@"
}

source sub "$BASH_SOURCE" "$@"
