#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  fogg default
  fogg check
  fogg plan
}

source sub "$BASH_SOURCE" "$@"
