#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ -f ".fogg-name" ]]; then
    cat .fogg-name
  else
    cat ".fogg-name-$(tf workspace show)"
  fi
}

source sub "$BASH_SOURCE" "$@"
