#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" source normalize

  local nm_color="${BASH_SOURCE##*-}"

  exec fogg account fogg color dispatch "${nm_color}" "$@"
}

source sub "$BASH_SOURCE" "$@"
