#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  exec aws "$(cat terraform.tf.json | jq -r '.variable.region.default')" exec fogg chamber "$(cat .fogg-name | cut -d/ -f2- | tr / -)" "$@"
}

source sub "$BASH_SOURCE" "$@"
