#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_workspace="$1"; shift
  tf workspace \select "$nm_workspace"
  fogg default
  if [[ "$#" -gt 0 ]]; then
    fogg "$@"
  fi
}

source sub "$BASH_SOURCE" "$@"
