#!/usr/bin/env bash

function gen {
  local tmp_state="$1"; shift
  local tmp_seed="$1"; shift
  local tmp_modules="$1"; shift

  local az_count="$(hcltool terraform.tfvars | jq -r '.az_count')"

	jq -n \
        --argfile state   "$tmp_state" \
        --argfile seed    "$tmp_seed" \
        --argfile modules "$tmp_modules" \
        '$state * $seed * $modules'
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source _fogg "$@"
}

source sub "$BASH_SOURCE" "$@"
