#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  echo aaa
}

main
source sub-middleware "$BASH_SOURCE" "$@"
