#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local id_tfvars
  if [[ -n "${1:-}" ]]; then
    id_tfvars="$1"; shift
  else
    id_tfvars="$(cat .fogg-name)"
  fi

  credstash get "$id_tfvars"
}

source sub "$BASH_SOURCE" "$@"
