#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  fogg
  terraform get
  terraform validate
  terraform plan -no-color -out .plan "$@"
}

source sub "$BASH_SOURCE" "$@"
