#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  exec fogg env vagrant "$@"
}

source sub "$BASH_SOURCE" "$@"
