#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local id_tfvars="$(cat .fogg-name)"
  exec credstash put "$id_tfvars" "$@"
}

source sub "$BASH_SOURCE" "$@"
