#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  terraform validate
  terraform apply -auto-approve=true .plan "$@"
  rm -f .plan
}

source sub "$BASH_SOURCE" "$@"
