#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_org=

  case "$(uname -s)" in
    Darwin)
      nm_org="$(cd ./$(git rev-parse --show-cdup) 2>/dev/null && cat .terraform/environment 2>/dev/null || true)"
      ;;
  esac

  
  exec ${nm_org} "$@"
}

source sub "$BASH_SOURCE" "$@"
