#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  eval $(fogg env)
  exec "$@"
}

source sub "$BASH_SOURCE" "$@"
