#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ "$#" == 0 ]]; then
    set -- list-container-instances
  fi

  local nm_cmd="$1"; shift
  case "$nm_cmd" in
    list-task-definitions)
      aws ecs "$nm_cmd" --family-prefix="${fogg_env}-${fogg_app}-${fogg_service}" "$@"
      ;;
    *)
      aws ecs "$nm_cmd" --cluster="${fogg_env}-${fogg_app}-${fogg_service}" "$@"
      ;;
  esac
}


__fogg_ecs_pwd="$(fogg name)"
export fogg_env="$(basename $(dirname $(dirname $__fogg_ecs_pwd)))" fogg_app="$(basename $(dirname $__fogg_ecs_pwd))" fogg_service="$(basename $__fogg_ecs_pwd)"

source sub "$BASH_SOURCE" "$@"
