#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local id_tfvars="org--$(cat .fogg-name | perl -pe 's{/}{--}g')/terraform.tfvars"

  exec credstash get "$id_tfvars" "$@"
}

source sub "$BASH_SOURCE" "$@"
