#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local pth_save="$(pwd)"
  cd -P .
  while [[ "$(pwd)" != "/" ]]; do
    if [[ -d .terraform ]]; then
      eval $(fogg env)
      break
    fi
    cd ..
  done

  cd "$pth_save"
  exec vagrant "$@"
}

source sub "$BASH_SOURCE" "$@"
