#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source normalize

  local nm_fogg="$(fogg name | cut -d/ -f2-)/"
  local id_credstash_org="org/$(echo "$nm_fogg" | cut -d/ -f1)"
  local id_credstash_local="$(fogg name)"

  local tmp_org="$(mktemp -t XXXXXX)"
  local tmp_local="$(mktemp -t XXXXXX)"

  trap "$(printf 'rm -f %q %q %q' "$tmp_org" "$tmp_local")" EXIT

  credstash get "$id_credstash_org" > "$tmp_org" 2>/dev/null &
  credstash get "$id_credstash_local" > "$tmp_local" 2>/dev/null &
  wait

  if [[ ! -s "$tmp_local" ]]; then
    echo '{}' > "$tmp_local"
  fi

  local nm_config="$(echo "$nm_fogg" | cut -d/ -f4-)"
  if [[ -z "$nm_config" ]]; then
    nm_config="$(echo "$nm_fogg" | cut -d/ -f3)"
    if [[ -z "$nm_config" ]]; then
      nm_config="$(echo "$nm_fogg" | cut -d/ -f2)"
      if [[ -z "$nm_config" ]]; then
        nm_config="$(echo "$nm_fogg" | cut -d/ -f1)"
      fi
    fi
  fi

  cat "$tmp_org" | jq \
    --arg org "$(echo "$nm_fogg" | cut -d/ -f1)" \
    --arg env "$(echo "$nm_fogg" | cut -d/ -f2)" \
    --arg app "$(echo "$nm_fogg" | cut -d/ -f3)" \
    --arg svc "$(echo "$nm_fogg" | cut -d/ -f4)" \
    --arg config "$nm_config" \
    --argfile local "$tmp_local" \
    '. + {"":{inherit:{},vars:{}}} | .[$org].inherit + .[$env].inherit + .[$app].inherit + .[$svc].inherit + .[$config].inherit + .[$config].vars + $local' | jq -S .
}

source sub "$BASH_SOURCE" "$@"
