#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile virtualenv
  localhost -m file -- state=link src=../vendor/virtualenv/bin/hcltool dest="$shome/bin/hcltool"
}

main "$@"
