#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  mkdir -p "$shome/bin"

  block compile pipenv
  ln -nfs "$(pipenv run which hcltool)" "$shome/bin/"
}

main "$@"
