#!/usr/bin/env bash

function main {
  local shome="${_fogg_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  ln -nfs ../vendor/virtualenv/bin/hcltool "$shome/bin/"
}

main
